version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\nim4\DBShield

environment:
  GOPATH: c:\gopath
  GOROOT: c:\go-x86

install:
  - echo %PATH%
  - echo %GOPATH%
  - echo %GOROOT%
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - go test -v ./...
