version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\nim4\DBShield
shallow_clone: true

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - go version
  - go env
  - go get -v -d -t ./...

build_script:
  - go install -v ./...

test_script:
  - go test -v ./...
